### ISSUE TITLE
Set a Default Value to yCollab for The First Co-User

### ISSUE THREAD

**Issue by cqh963852** [yjs/y-codemirror.next#23]
**Is your feature request related to a problem? Please describe.**
I am creating a collab script editor.  It can fetch script from backend, then store is in memfs.

While Open the editor, I don't know how to give a initila value to yCollab.

If give initContent to `EditorState.create`, some strange things happen

![image](https://user-images.githubusercontent.com/17702287/205188669-535d6953-cc9f-4d49-9519-ccfddc8a483d.png)

```
export const createEditor = (params: {
  el: HTMLElement;
  provider: WebrtcProvider;
  onSave?: () => boolean;
  initContent?: string;
}) => {
  const { el, provider, onSave, initContent } = params;

  const ydoc = provider.doc;
  const ytext = ydoc.getText("codemirror");

  const undoManager = new Y.UndoManager(ytext);

  provider.awareness.setLocalStateField("user", {
    name: "Anonymous " + Math.floor(Math.random() * 100),
    color: userColor.color,
    colorLight: userColor.light,
  });

  const collabExt = yCollab(ytext, provider.awareness, { undoManager });

  // if (ytext.toJSON().length === 0 && initContent) ytext.insert(0, initContent);

  const state = EditorState.create({
    doc: initContent,
    extensions: [
      basicSetup,
      javascript(),
      collabExt,
      keymap.of([
        {
          key: "Ctrl-s",
          run: onSave,
        },
      ]),
    ],
  });

  const view = new EditorView({
    state,
    parent: el,
  });

  return {
    view,
  };
};

```

**Describe the solution you'd like**
I haven't figured out how y-codemirror.next works.

If adding a parameter, will it make the user more clear how to use the default data

```
const collabExt = yCollab(ytext, provider.awareness, { undoManager, initContent });
```

**Comment by dmonad** [comment]
Hi @cqh963852,

I don't recommend setting the "initial value" on the client side. What would happen if two clients joined simultaneously? Both would initialize the content, henco you would end up with duplicate content. This should be handled by the server if there is any, or when creating the document.

You can search for more elaborate answers & solutions on our discussion board: discuss.yjs.dev (search for "initial content").
