### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by frenzymadness** [yjs/y-codemirror.next#25]
Hello.

Could you please add a LICENSE file to the repository? It's defacto standard to have. It also seems that the license specification is missing somewhere in the configuration because on npmjs.com the license field has "none".

![image](https://user-images.githubusercontent.com/5688939/218674603-bda2e361-c465-42ed-9abc-bd960347093c.png)

Thank you.

**Comment by dmonad** [comment]
Thanks. I added my usual license and added the package.json field. This should be available in the next release.
