### ISSUE TITLE
Bump @codemirror peer dependencies to include 0.19?

### ISSUE THREAD

**Issue by yurikhan** [yjs/y-codemirror.next#3]
**Is your feature request related to a problem? Please describe.**

The current version of `@codemirror/state` is 0.19.2 and `@codemirror/view` is 0.19.9. `y-codemirror.next` specifies `^0.18.0` and this excludes 0.19.*, as far as I understand, because 0._x_._y_ versions are considered to break on every _x_ increment.

As far as I can tell (which is, admittedly, not very far), `y-codemirror.next` continues to function if `@codemirror/*` packages are upgraded to 0.19.*, except that npm reports a broken peer dependency.

**Describe the solution you’d like**

It would be nice if someone knowledgeable about both Yjs and CodeMirror 6 were to review the changes listed as breaking [in `@codemirror/state` 0.19.0](https://github.com/codemirror/state/blob/main/CHANGELOG.md#breaking-changes) and [in `@codemirror/view` 0.19.1](https://github.com/codemirror/view/blob/main/CHANGELOG.md#breaking-changes), and either support them in `y-codemirror.next` or declare that no changes are needed and bump the peer dependency versions to maybe `^0.18.0 || ^0.19.0` or `>= 0.18.0 <0.20`.

**Describe alternatives you’ve considered**

For the application I’m trying to develop, staying on CodeMirror 6 0.18 is suboptimal because 0.19 seems to fix some user-visible bugs.

I don’t want to build with CodeMirror 5 now and have to migrate to 6 later, as that would incur twice the integration effort.

**Comment by dmonad** [comment]
Hi @yurikhan,

I bumped the dependencies and published a new release `v0.1.0`. My plan is to keep supporting the latest version of `@codemirror/*` without backward compatibility until there is a major @codemirror release.
