### ISSUE TITLE
Import of type-only types in bundled JS breaks build

### ISSUE THREAD

**Issue by ErikSchierboom** [yjs/y-codemirror.next#9]
**Describe the bug**

The `y-codemirror.next` package contains invalid JS that causes `esbuild` to break.
Several files in the package import types from `@codemirror/X` packages that are not exported by that package.
As it turns out, all those types are used in type annotation comments (which makes sense as they can't be used in code as they're not exported).
As these types are not actually exported, `esbuild` (correctly) produces an error like: `No matching export in "node_modules/@codemirror/X/dist/index.js" for import "Y"`

Here are some links to the source:

- First, the file that imports the `DecorationSet` type: https://github.com/yjs/y-codemirror.next/blob/main/src/y-remote-selections.js#L2
- Then, the type annotation comment that uses the `DecorationSet` type: https://github.com/yjs/y-codemirror.next/blob/main/src/y-remote-selections.js#L129
- The imported package's code looks like this: https://unpkg.com/@codemirror/view@0.19.43/dist/index.js (scroll down to the last line to see the exports: no `DecorationSet` exported)
- The imported package's `d.ts` looks like this: https://unpkg.com/@codemirror/view@0.19.43/dist/index.d.ts (scroll down to the last line to see the exports: the `DecorationSet` is exported)

**To Reproduce**

Go to https://stackblitz.com/edit/node-jla3pz?file=package.json

In the console, do:

```shelll
> npm install
```

Then do:

```shell
> npm run build
```

You should then see the following errors:

```shell
❯ npm run build
$ esbuild index.js --bundle --outfile=out.js --external:vue --format=esm
✘ [ERROR] No matching export in "node_modules/@codemirror/view/dist/index.js" for import "DecorationSet"

    node_modules/y-codemirror.next/src/y-remote-selections.js:2:57:
      2 │ ..., EditorView, Decoration, DecorationSet, WidgetType } from '@cod...
        ╵                              ~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@codemirror/state/dist/index.js" for import "StateCommand"

    node_modules/y-codemirror.next/src/y-undomanager.js:3:15:
      3 │   EditorState, StateCommand, Facet, Annotation, AnnotationType // e...
        ╵                ~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@codemirror/view/dist/index.js" for import "KeyBinding"

    node_modules/y-codemirror.next/src/y-undomanager.js:6:33:
      6 │ ... { ViewPlugin, ViewUpdate, KeyBinding, EditorView } from '@codem...
        ╵                               ~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@codemirror/state/dist/index.js" for import "Extension"

    node_modules/y-codemirror.next/src/index.js:4:9:
      4 │ import { Extension } from '@codemirror/state' // eslint-disable-line
        ╵          ~~~~~~~~~

4 errors
```

**Expected behavior**

The package should by default (without any modifications) also build using `esbuild`.

**Environment Information**
 - Browser: Chrome
 - Packages:
  - "@codemirror/basic-setup": "^0.19.0",
  - "@codemirror/lang-javascript": "^0.19.0",
  - "@codemirror/state": "^0.19.0",
  -  "@codemirror/view": "^0.19.0",
  -  "y-codemirror.next": "^0.1.0",
  -  "y-websocket": "^1.3.18",
  -  "yjs": "^13.5.22"
  -  "esbuild": "^0.14.22"

**Additional context**

The [demo project](https://github.com/yjs/yjs-demos/tree/main/codemirror.next) in the `yjs-demos` project _does_ work, but that is very likely due to it using `webpack` and webpack doing some transformations on the source code.

Also see https://github.com/evanw/esbuild/issues/2029 for the original discussion on `esbuild`'s repo.

**Comment by dmonad** [comment]
I fixed the issue. I'm not very happy about this approach and I hope that esbuild will eventually ignore non-existent imports as the other bundlers do.

Feel free to reopen the issue if I missed something.

**Comment by ErikSchierboom** [comment]
Thanks a lot!
